services:
  frontend:
    build:
      context: ./chat-app
    ports:
      - "3000:3000"
    depends_on:
      - db
  backend:
    build:
      context: ./chat-app-backend
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    volumes:
      - tech_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"
volumes:
  tech_db: